language: python
python: 3.3
env:
  - TOX_ENV=py26
  - TOX_ENV=py27
  - TOX_ENV=py32
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35

install:
  - pip install -r requirements.txt
  - pip install tox

script:
  - tox -e $TOX_ENV

notifications:
  email:
    on_success: change
    on_failure: change
